### ISSUE TITLE
IntervalUtility output implementation 

### ISSUE THREAD

**Issue by wangengzheng** [AlexeyBoiko/IntervalUtility#1]
- [ Not Bug ] 

hi AlexeyBoiko
You created a great library
[Online example](https://alexeyboiko.github.io/IntervalUtility/)

I am very interested in how your console outpu is rendered
          2              5         7         9                                                      
          |--------------|         |---------|                                                      
0              3    4         6    7              10                                                
|--------------|    |---------|    |--------------|                                                 
     1              4    5              8                                                           
     |--------------|    |--------------|                                                           
Result
          2    3                   7    8                                                           
          |----|                   |----|   

The large number range on your website does not display properly

This is the screenshot
![image](https://user-images.githubusercontent.com/12171338/137575396-9e67b052-bc0f-4cdd-be35-4b0d0001e63c.png)

I am very interested in how you wrote it 

Can this part of the code be written in the integration test? It’s very intuitive to see

**Comment by AlexeyBoiko** [comment]
Hello wangengzheng,
Code of "Online example" is dirty, so I don't want to make it public. I send you invitation to the repo.
Also AsciiDrawer maybe intrested for you.
https://alexeyboiko.github.io/AsciiDrawerSite/
